backend:
  name: git-gateway
  branch: master
media_folder: "images/uploads"
collections:
  - name: "menu" # Used in routes, e.g., /admin/collections/blog
    label: "Menu Items" # Used in the UI
    folder: "menu" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "tags", name: "tags", widget: "hidden", default: "menu" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
